services:

  ubuntu:
    container_name: box
    hostname: box
    build: build/.
    env_file:
      - .env
    volumes:
      - ./home/:/home/me # HOME
      - ./opt:/opt/box # BOX scripts
      - ../services:/data/services # box scripts
      - ../terraform:/data/terraform
