services:

  ubuntu:
    container_name: box
    hostname: box
    build: build/.
    env_file:
      - ../config/.env
    volumes:
      - ./home/:/home/me # HOME
      - ./opt:/opt/box # BOX scripts
      - ../services:/data/services # Applications
      - ../terraform:/data/terraform  # Infrastructure
      - ../config/.env:/data/config/.env # Config file (read/write)
