#!/bin/bash

start_time=$(date +%s.%3N)

for f in /opt/box/libs/* ; do source $f; done
export PATH+=':/opt/box/bin'

# Load and export configuration
load_config() {
    if [ -f /data/config/.env ]; then
        
        set -a # Enable automatic export of all variables
        source /data/config/.env
        set +a # Disable automatic export
        
        debug "Loaded and exported all configuration variables from /data/config/.env"
    else
        error "Config file /data/config/.env not found"
        exit 1
    fi
}

load_config

main_usage() {
    echo "----------------- box -----------------" 
    echo "wrappers around various CLIs" 
    echo "box [-h] [-d] [command] ... "
    echo "    -h              : this helper"
    echo "    -d              : enable debug mode"
    echo "    hello           : hello world"
    echo "    ssh ...         : ssh wrapper"
    echo "    deploy ...      : deploy tools"
    echo "    terraform ...   : terraform wrappers"
    echo "    dns ...         : DNS zone management"
}

while getopts "hd" option; do
case ${option} in
    h) main_usage && exit 0 ;;
    d) 
        export DEBUG=1 
        notice "debug mode on" ;
    ;;
    *) usage && exit 1 ;;
    esac
done

shift $(($OPTIND-1))
CMD=${1} && shift 1

debug command=$CMD
/opt/box/${CMD}.sh $@

end_time=$(date +%s.%3N)
debug "$(echo $end_time - $start_time | bc)s"