#!/bin/bash

start_time=$(date +%s.%3N)

for f in /opt/box/libs/* ; do source $f; done
export PATH+=':/opt/box/bin'

# Load and export configuration
load_config() {
    if [ -f /data/config/.env ]; then
        
        set -a # Enable automatic export of all variables
        source /data/config/.env

        export SSH_HOST="${DEPLOY_USER}@${SUBDOMAIN}.${DOMAIN}"

        set +a # Disable automatic export
        
        debug "Loaded and exported all configuration variables from /data/config/.env"
    else
        error "Config file /data/config/.env not found"
        exit 1
    fi
}

load_config

# Show debug status if enabled
[ "${DEBUG}" = "1" ] && debug "debug mode active inside container"

# Get command and shift arguments
if [ -z "$1" ]; then
    error "No command specified"
    exit 1
fi
CMD="$1"
shift 1

debug command=$CMD
/opt/box/${CMD}.sh "$@"

end_time=$(date +%s.%3N)
debug "$(echo $end_time - $start_time | bc)s"