#!/bin/bash

start_time=$(date +%s.%3N)

for f in /opt/box/libs/* ; do source $f; done
export PATH+=':/opt/box/bin'

main_usage() {
    echo "----------------- box -----------------" 
    echo "wrappers around various CLIs" 
    echo "box [-h] [-d] [command] ... "
    echo "    -h              : this helper"
    echo "    hello           : hello world"
    echo "    backup          : backup & restore tools"
    echo "    transfer        : transfer data from grosserver1.0 to grosserver2.0"
    echo "    ssh ...         : ssh wrapper"
    echo "    deploy ...      : deploy tools"
    echo "    terraform ...   : terraform wrappers"
}

while getopts "hd" option; do
case ${option} in
    h) main_usage && exit 0 ;;
    *) usage && exit 1 ;;
    esac
done

if [ -n "${DEBUG}" ] ; then notice "debug mode on" ; fi 

shift $(($OPTIND-1))
CMD=${1} && shift 1

debug command=$CMD
/opt/box/${CMD}.sh $@

end_time=$(date +%s.%3N)
debug "$(echo $end_time - $start_time | bc)s"